version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "next-auth"
    versions: ["4.x", "5.x"]
  - dependency-name: "node-fetch"
    versions: ["3.x", "4.x"]
  - dependency-name: "@types/next-auth"
    versions: ["3.x", "4.x"]
