version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "next-auth"
  - dependency-name: "node-fetch"
  - dependency-name: "@types/next-auth"
